inherit_gem:
  rubocop-rails:
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/BlockDelimiters:
  StyleGuide: '#single-line-blocks'
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
